# Install netbeans debian package
- name: Install netbeans debian package
  apt:
    deb: https://archive.apache.org/dist/netbeans/netbeans-installers/18/apache-netbeans_18-1_all.deb

#- name: install netbeans
#  shell: |
#    cd /tmp
#    wget -q https://archive.apache.org/dist/netbeans/netbeans-installers/18/apache-netbeans_18-1_all.deb
#    dpkg -i apache-netbeans_18-1_all.deb
#    apt install -f -y
#  become: yes