- name: apt key for vscode
  apt_key: url=https://packages.microsoft.com/keys/microsoft.asc state=present
- name: apt repo for vscode
  apt_repository: repo="deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" update_cache=yes filename="vscode"

- name: install vscode
  apt:
    state: present
    pkg: code

# Install extensions:
- name: make sure vscode extension directory exists
  file: path=/opt/vscode/extensions state=directory
  
- name: vscode extensions
  shell: code --extensions-dir /opt/vscode/extensions --user-data-dir /opt/vscode --no-sandbox --install-extension {{ item }}
  loop: "{{ vscode_extensions }}"

# https://stackoverflow.com/questions/69706490/where-does-vscode-store-the-enabled-disabled-state-for-extensions
- name: disable by default the extensions that cause the keybinds to change
  shell: code --extensions-dir /opt/vscode/extensions --user-data-dir /opt/vscode --no-sandbox --disable-extension {{ item }}
  loop:
    - vscodevim.vim
    - lfs.vscode-emacs-friendly
  ignore_errors: yes

- name: create a script to symlink our extensions
  copy:
    dest: /usr/local/bin/vscode-extension-install
    mode: 0755
    content: |
      #!/bin/bash
      mkdir -p $HOME/.vscode
      ln -sf /opt/vscode/extensions $HOME/.vscode/extensions

- name: add vscode extension install script to autostart
  copy:
    dest: /etc/xdg/autostart/vscode-extension-install.desktop
    content: |
      [Desktop Entry]
      Type=Application
      Exec=/usr/local/bin/vscode-extension-install
      NoDisplay=true

# Configure VS Code settings
- name: create vscode User settings directory
  file: path=/opt/vscode/User state=directory

- name: create vscode settings.json
  copy:
    dest: /opt/vscode/User/settings.json
    content: |
      {
        "extensions.autoUpdate": false,
        "extensions.ignoreRecommendations": true
      }
