---
- name: java openjdk
  apt:
    state: present
    pkg:
      - openjdk-21-jdk
      - openjdk-21-doc   # Updated to match ICPC 2025 standards
      - openjdk-21-source   # Updated to match ICPC 2025 standards

- name: register docs
  block:
    - ansible.utils.update_fact:
        updates:
          - path: "lang_docs['Java']"
            value:
              name: Java API Documentation
              id: java_api
              path: /usr/share/doc/openjdk-11-doc/api
              index: index.html
      register: updated
    - set_fact:
        lang_docs: "{{ updated.lang_docs }}"
