---
- name: java openjdk
  apt:
    state: present
    pkg:
      - openjdk-21-jdk
      - openjdk-21-doc   # 246 mb
      - openjdk-21-source   # 60 mb

- name: register docs
  block:
    - ansible.utils.update_fact:
        updates:
          - path: "lang_docs['Java']"
            value:
              name: Java API Documentation
              id: java_api
              path: /usr/share/doc/openjdk-21-doc/api
              index: index.html
      register: updated
    - set_fact:
        lang_docs: "{{ updated.lang_docs }}"
